<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('currencies',function(Blueprint $t){$t->id();$t->char('code',3)->unique();$t->string('name');$t->string('symbol',8);$t->unsignedTinyInteger('decimal_places')->default(2);$t->decimal('rate_to_base',18,8)->default(1);$t->boolean('is_base')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('markets',function(Blueprint $t){$t->id();$t->string('name');$t->string('code',20)->unique();$t->char('country_code',2);$t->foreignId('currency_id')->constrained();$t->string('timezone')->default('UTC');$t->boolean('is_default')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('categories',function(Blueprint $t){$t->id();$t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->string('image_url')->nullable();$t->integer('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('brands',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('origin_country',2)->nullable();$t->text('description')->nullable();$t->string('logo_url')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('brand_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->text('short_description')->nullable();$t->longText('description')->nullable();$t->longText('ingredients')->nullable();$t->longText('usage_instructions')->nullable();$t->string('status',20)->default('draft')->index();$t->boolean('track_inventory')->default(true);$t->string('seo_title')->nullable();$t->text('seo_description')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('product_variants',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('sku')->unique();$t->string('barcode')->nullable()->unique();$t->string('title')->nullable();$t->json('option_values')->nullable();$t->unsignedInteger('weight_grams')->nullable();$t->decimal('cost_price',16,4)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('product_media',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('type',20)->default('image');$t->string('url');$t->string('alt_text')->nullable();$t->integer('sort_order')->default(0);$t->timestamps();});
  Schema::create('product_market_prices',function(Blueprint $t){$t->id();$t->foreignId('variant_id')->constrained('product_variants')->cascadeOnDelete();$t->foreignId('market_id')->constrained()->cascadeOnDelete();$t->foreignId('currency_id')->constrained();$t->decimal('price',16,4);$t->decimal('compare_at_price',16,4)->nullable();$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['variant_id','market_id','is_active']);});
  Schema::create('warehouses',function(Blueprint $t){$t->id();$t->foreignId('market_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('code')->unique();$t->json('address')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('inventory_stocks',function(Blueprint $t){$t->id();$t->foreignId('variant_id')->constrained('product_variants')->cascadeOnDelete();$t->foreignId('warehouse_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('on_hand')->default(0);$t->unsignedInteger('reserved')->default(0);$t->unsignedInteger('damaged')->default(0);$t->unsignedInteger('reorder_level')->default(10);$t->timestamps();$t->unique(['variant_id','warehouse_id']);});
  Schema::create('inventory_movements',function(Blueprint $t){$t->id();$t->foreignId('variant_id')->constrained('product_variants')->cascadeOnDelete();$t->foreignId('warehouse_id')->constrained()->cascadeOnDelete();$t->string('type',30);$t->integer('quantity');$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['variant_id','warehouse_id','created_at']);});
 }
 public function down():void { foreach(['inventory_movements','inventory_stocks','warehouses','product_market_prices','product_media','product_variants','products','brands','categories','markets','currencies'] as $table) Schema::dropIfExists($table); }
};
