<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('customers',function(Blueprint $t){$t->id();$t->string('first_name');$t->string('last_name')->nullable();$t->string('email')->nullable()->index();$t->string('phone')->nullable()->index();$t->string('status',20)->default('active');$t->json('tags')->nullable();$t->text('notes')->nullable();$t->boolean('marketing_opt_in')->default(false);$t->timestamps();});
  Schema::create('customer_addresses',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->string('type',20)->default('shipping');$t->string('first_name');$t->string('last_name')->nullable();$t->string('phone')->nullable();$t->string('line1');$t->string('line2')->nullable();$t->string('city');$t->string('state')->nullable();$t->string('postal_code')->nullable();$t->char('country_code',2);$t->boolean('is_default')->default(false);$t->timestamps();});
  Schema::create('coupons',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->string('type',20);$t->decimal('value',16,4);$t->decimal('min_spend',16,4)->nullable();$t->decimal('max_discount',16,4)->nullable();$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->unsignedInteger('max_uses')->nullable();$t->unsignedInteger('max_uses_per_customer')->nullable();$t->json('rules')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('orders',function(Blueprint $t){$t->id();$t->string('order_number')->unique();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('market_id')->constrained();$t->foreignId('warehouse_id')->constrained();$t->char('currency_code',3);$t->string('status',30)->default('pending')->index();$t->string('payment_status',30)->default('pending')->index();$t->string('fulfillment_status',30)->default('unfulfilled')->index();$t->decimal('subtotal',16,4);$t->decimal('discount_total',16,4)->default(0);$t->decimal('shipping_total',16,4)->default(0);$t->decimal('tax_total',16,4)->default(0);$t->decimal('grand_total',16,4);$t->string('coupon_code')->nullable();$t->text('notes')->nullable();$t->timestamp('placed_at')->nullable();$t->timestamps();$t->index(['market_id','placed_at']);});
  Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete();$t->string('sku');$t->string('name');$t->unsignedInteger('quantity');$t->decimal('unit_price',16,4);$t->decimal('discount_total',16,4)->default(0);$t->decimal('tax_total',16,4)->default(0);$t->decimal('line_total',16,4);$t->timestamps();});
  Schema::create('order_addresses',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('type',20);$t->string('first_name');$t->string('last_name')->nullable();$t->string('phone')->nullable();$t->string('email')->nullable();$t->string('line1');$t->string('line2')->nullable();$t->string('city');$t->string('state')->nullable();$t->string('postal_code')->nullable();$t->char('country_code',2);$t->timestamps();});
  Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('provider')->nullable();$t->string('method');$t->string('transaction_reference')->nullable()->index();$t->string('status',30);$t->decimal('amount',16,4);$t->char('currency_code',3);$t->json('payload')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
  Schema::create('shipments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('carrier')->nullable();$t->string('service')->nullable();$t->string('tracking_number')->nullable()->index();$t->string('status',30)->default('pending');$t->decimal('shipping_cost',16,4)->default(0);$t->string('label_url')->nullable();$t->timestamp('shipped_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
 }
 public function down():void { foreach(['shipments','payments','order_addresses','order_items','orders','coupons','customer_addresses','customers'] as $table) Schema::dropIfExists($table); }
};
